### ISSUE TITLE
Dual-Channel and Hierarchical Graph Convolutional Networks for document-level relation extraction

### ISSUE THREAD

**Issue by jzhang38** [QiSun123/SAR#1]
Sun Qi 同学你好，

最近阅读了您的工作  Dual-Channel and Hierarchical Graph Convolutional Networks for document-level relation extraction 并且非常感兴趣。
请问能否分享一下您的代码。
我的邮件:peiyuan_zhang@mymail.sutd.edu.sg。
谢谢！

**Comment by QiSun123** [comment]
培元 同学你好，

非常感谢您的关注！
因为代码涉及医学保密项目，所以没有公开，但是论文承诺的数据，我们已经开放，更多方法细节，欢迎继续讨论！

谢谢！
